name: test

on:
  push:
  pull_request:

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run shellcheck
        run: shellcheck generate-monorepo.sh

  bats:
    name: bats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install bats and zip
        run: sudo apt-get update && sudo apt-get install -y bats zip unzip
      - name: Run bats tests
        run: bats test/
